### ISSUE TITLE
Docstrings in header

### ISSUE THREAD

**Issue by blitzher** [blitzher/P4-lang#101]
There should be docstrings to ALL functions, classes and methods in the header.

Docstrings look like this;

```c
/**
 * @brief Convert a unit alias into the standard, i.e. 'grams' to 'g'.
 *
 * @param unit Unit to standardize
 * @return std::string The standard for a specific unit alias
 */
 std::string AmountConverter::standardize(std::string unit);

```

**Comment by Lildhansen** [comment]
i'll do parser

**Comment by NikolajKrogh** [comment]
- [x] Lexer
- [x] Parser
- [x] Visitor
- [x] utility
- [x] epicr functions

these:

![image](https://user-images.githubusercontent.com/57398300/166641982-70b34ec3-30c2-460d-868d-7e9df157bfc6.png)

**Comment by Lildhansen** [comment]
parser er done for alle funktioner i hvert fald (ved ikke om det måske er worth også at gøre det for nogle af dens properties)

**Comment by Jaffenheimer** [comment]
All has been ticked off closing this
