### ISSUE TITLE
mandatory-field test

### ISSUE THREAD

**Issue by Lildhansen** [blitzher/P4-lang#108]
synes der skal lave tests for alle mandatory fields i visitor test. (altså en test hvor hver af dem mangler så den expecter at få en bestemt fejlmeddelse)

derudover synes jeg at for den test der er nu (som altså tjekker der ikke er fejl) skal bruge en mere basic fil (eller string) - hvor der kun er det bare minimum - da det jo er en unit test og vi ikke skal teste for alle mulige andre fejl (fx hvis der er fejl i time fejler den her test, selvom den intet med det har at gøre)

**Comment by Lildhansen** [comment]
hvis vi altså stadig vil have mandatory fields

**Comment by RedToad0** [comment]
Ja det er jo spørgsmålet... folk?

**Comment by Jaffenheimer** [comment]
Der var en issue igår, vi fixede issuen igår, but dunno
