### ISSUE TITLE
readingredients har errors som (måske) burde være warnings (i følge comments i hvert fald)

### ISSUE THREAD

**Issue by Lildhansen** [blitzher/P4-lang#116]

**Comment by blitzher** [comment]
Jeg ved hvad koden du referer til, men tag lige at sæt et linjetal eller kodesnippet ind når du laver sådan en issue.

**Comment by Lildhansen** [comment]
der står readIngredient - som er en funktion som man altid kan finde. hvis jeg sætter linjetal på er der en chance for at der tilføjes/slettes noget over så linjetallet ikke passer. vil sige det er mere sigende at jeg giver funktionsnavnet. men du kan godt få linje 439 og 452

**Comment by Lildhansen** [comment]
eller søg efter "warning" i parser.cpp
