### ISSUE TITLE
Nogen må gerne læse semantics grundigt igennem, og kontrollere at reglerne er korrekte 

### ISSUE THREAD

**Issue by KasperBahrentzAAU** [blitzher/P4-lang#125]

**Comment by blitzher** [comment]
Please add a description to your issue, before submitting. This was done automatically.

**Comment by Jaffenheimer** [comment]
Det er da vist christian der skal det hahahaha

**Comment by RedToad0** [comment]
i forhold til hvad programmet gør eller om semantics er sketch?

**Comment by NikolajKrogh** [comment]
Jeg synes de ser fine ud

**Comment by Jaffenheimer** [comment]
Same

**Comment by Lildhansen** [comment]
👍
