### ISSUE TITLE
TODO: Recognise command line arguments

### ISSUE THREAD

**Issue by blitzher** [blitzher/P4-lang#13]
Write specification of which command line arguments are desired, such as

- Output file location/name
- Styling options for the html output
- Parsing/Visitor style, provide all warnings or as few as possible (?)
- etc.

and recognise these from the command line arguments given to the compiler, and put into a global scope for each component to read from, in a simple format.

**Comment by blitzher** [comment]
Updated the issue description to more accurately describe the current decision.
The output JavaScript is in charge of converting between imperial and metric, along with scaling up or down the recipe, to fit the servings amount.

**Comment by Jaffenheimer** [comment]
Implemented GUI and it is working
