### ISSUE TITLE
Naming of referenced ingredients

### ISSUE THREAD

**Issue by KasperBahrentzAAU** [blitzher/P4-lang#143]
Currently, when _declaring_ ingredient references, they must be named with the name of the recipe file.
However, when _using_ these ingredients, the name of the **title** of that recipe must be used.
This is confusing and should be changed, so that it is always the file name.

**Comment by blitzher** [comment]
Hvorfor er denne blevet genåbnet?

**Comment by blitzher** [comment]
Re-resolved in b77e54b4696dbce4cd0f058630beb63f5eaa5b33
