### ISSUE TITLE
vores sprog er somehow ikke case insentive for ingredienser mere

### ISSUE THREAD

**Issue by Lildhansen** [blitzher/P4-lang#147]
ved pt lige nu kun at det er mellem ingredient list og ingredients i instruction

**Comment by Lildhansen** [comment]
i AM sane

**Comment by blitzher** [comment]
Har du skrevet en/flere unit tests til at se det? Hvor kommer problemet fra, er det et visitor, parser eller lexer problem?

**Comment by Lildhansen** [comment]
er først lige begyndt at kigge på det nu
