### ISSUE TITLE
Error messages i gui

### ISSUE THREAD

**Issue by Jaffenheimer** [blitzher/P4-lang#158]
Hvis der sker fejl i compileringen skal der komme en fejlbesked i GUI'en på en eller anden måde.

**Comment by RedToad0** [comment]
jeg kiggede lige lidt på det og fik en boks til at virke men var ikke sikker på hvordan man kan overføre error messages på en smart måde til python

**Comment by Jaffenheimer** [comment]
Har heller ikke lige nogen god løsning til denne

**Comment by RedToad0** [comment]
windows person @Lildhansen  pls check om det virker paa windows. Python er funky.

**Comment by blitzher** [comment]
Looks good on mac 😄 Det var også nogenlunde den approach jeg ville have taget, skrive i en fil og læse den igennem python.
Ville nok putte det i én fil i stedet for 2, og gøre filen til en gemt fil, i.e. give den et navn som `.epicr-error`, et punktum til start betyder generelt "don't look at me, unless 🔫"

**Comment by RedToad0** [comment]
Hov glemte mac.
Det du ønsker skal du få

**Comment by RedToad0** [comment]
Virker åbenbart ikke på windows.
Muligvis noget med at error filen ikke laves.

**Comment by NikolajKrogh** [comment]
Der burde ikke stå fejl som fx IngVer når det er til user. Der var flere i brugertest der sagde det var forvirrende
