### ISSUE TITLE
Servings mængde er weird.

### ISSUE THREAD

**Issue by RedToad0** [blitzher/P4-lang#162]
Eks. i basic output
### **Title:** Spaghetti carbonara
**Servings:** 4.000000 people

der kommer en hel masse decimaler, af hvad jeg hørte var det resultatet af et tidligere fix som holdte op med at virke. 
Det bliver håndteret i htmlen pt. men måske kunne det være rart at fikse servings i stedet for at rette i outputs?

**Comment by Jaffenheimer** [comment]
Det er vel fint at rette i output, nu når det bare er noget prettifying

**Comment by RedToad0** [comment]
feel free

**Comment by Jaffenheimer** [comment]
Then this is done

**Comment by Jaffenheimer** [comment]
This is not done in basic output, reopening

**Comment by Jaffenheimer** [comment]
This is resolved in [03a09bf](https://github.com/blitzher/P4-lang/commit/03a09bfdbcd260080abfc76162324d0b1ef7b735)
