### ISSUE TITLE
Implementation of pictures

### ISSUE THREAD

**Issue by RedToad0** [blitzher/P4-lang#165]
- [ ] CFG skal rettes
- [ ] Future work & evt. andre steder vi nævner at vi ikke bruger billeder skal ændres
- [x] Basic output mangler implementation af dette
- [ ] language specification skal rettes

**Comment by Jaffenheimer** [comment]
Synes ikke basic output skal have implementation af dette

**Comment by Lildhansen** [comment]
Skal der så være visitor der tjekker at det er et valid link eller hvad?

**Comment by blitzher** [comment]
Syntes at man gerne må lave en `todo` image header, så man skriver body og sådan noget, uden lige at have billedet klar.

**Comment by Lildhansen** [comment]
Hvorfor skal man overhovedet kunne skrive body/billedtekst til den?
