### ISSUE TITLE
procent og fractions skal beskrives i ingredient verifier visitor delen af rapporten

### ISSUE THREAD

**Issue by Lildhansen** [blitzher/P4-lang#168]

**Comment by blitzher** [comment]
Please add a description to your issue, before submitting. This was done automatically.

**Comment by RedToad0** [comment]
- [ ] language definition
- [ ] parser
- [ ] ingredient verifier

**Comment by RedToad0** [comment]
it is written but theres plenty of issues with fractions.... might need changes later
