### ISSUE TITLE
GUI filnavne med underscores

### ISSUE THREAD

**Issue by RedToad0** [blitzher/P4-lang#173]
bug af mindre prioritet som vi nok ikke skal fikse før andre ting
men hvis at du bruger _ i fil navne  og prøver at compile igennem GUIen
eks sej_opskrift.rpc vil den parse filnavnet 
opskrift.rpc

**Comment by Jaffenheimer** [comment]
Det virker apparently så lukker denne

**Comment by RedToad0** [comment]
look at shadows where there are none
