### ISSUE TITLE
Fractions and procentage in nutrients:

### ISSUE THREAD

**Issue by RedToad0** [blitzher/P4-lang#178]
Konkret hvis at du skriver
- protein [half],
- fat [1/3],
- carbs [20%]

Bliver det i outputtet conventeret til 
- protein (0 )
- fat (0.33 %)
- carbs (0.20 %)

Bonus spørgsmål:
Skal man kunne beskrive dem med både fractions og procent?  hvis at vi gør så vil de ikke længere kun relatere til 'relative amounts'

**Comment by blitzher** [comment]
Det skal bare ikke være tilladt at bruge relative mængder i nutrients, ingredients og kitchenware
