### ISSUE TITLE
QUESTION: How do we link to other recipes?

### ISSUE THREAD

**Issue by KasperBahrentzAAU** [blitzher/P4-lang#18]
I outputtet til f.eks. carbonara, står spaghetti som et hyperlink, fordi det i sig selv er en opskrift. Hvordan fungerer dette link? Skal alle brugerens opskrifter ligge i én mappe, så det er muligt at holde styr på det? Hvad nu hvis spaghetti opskriften ikke ligger i den mappe når man compiler carbonaraen, skal den så skabes of lægges derind? Skal brugeren have en zip-fil? How we do this?

**Comment by blitzher** [comment]
Se issue #17
