### ISSUE TITLE
Improve readability of lexer

### ISSUE THREAD

**Issue by KasperBahrentzAAU** [blitzher/P4-lang#29]

**Comment by blitzher** [comment]
More info plz

**Comment by KasperBahrentzAAU** [comment]
Er ikke helt med på den her compare struct.

`struct compare
{
    char key;
    compare(char const& i) : key(i) {}

    bool operator()(char const& i)
    {
        return (i == key);
    }
};`

Hvad er ios_base:cur her?

`                    /* since we encountered a non-blank, step back once */
                    if (!istream.eof()) /* can't seek when at EOF */
                        istream.seekg(-1, ios_base::cur);
                    break;`

The rest I understand

**Comment by blitzher** [comment]
### Compare Struct
`compare` structen skal ses som en lambda function, der bliver brugt til at checke om hvorvidt `char == char`. Årsagen til at den ligger i en fancy struct, er så den kan blive passet til en af de indbyggede funktionerne, igennem makroen `CH_V_CONTAINS`. Se kode nedenunder

```
#define CH_V_CONTAINS(ARR, VALUE) \
    (any_of(ARR.begin(), ARR.end(), compare(VALUE)))
```

Dette er også det eneste sted den bliver brugt. Kunne være lavet uden, men med den indbyggede funktion er det dejligt kort.

### ios base::cur
`ios_base::cur` er egentligt bare en enum, der fortællere `istream`'en hvilken retning/fra hvor den skal `seek`. Det kan være fx. fra starten af filen, slutningen af filen, eller relativt til hvor "cursoren" er lige nu. Det er det `cur` siger, at det er fra *current position*.
