### ISSUE TITLE
Parser issues

### ISSUE THREAD

**Issue by Lildhansen** [blitzher/P4-lang#39]
- håndtere at man skriver curly bois (og andre illegal chars) i teksten (evt give fejl eller bare springe over det)
- ~~skal kunne acceptere normale parenteser i tags~~
- ~~hvis der sættes mindst et komma før den første unit (altså i []), er der fejl~~
- Parser kan ikke læse tegn som é (é bliver læst som├®) - er det noget vi skal bekymre os om  (okay det er nok kun en fejl i terminalen)
- ~~hvis man staver et field forkert (eller skriver noget volapyk med kolon efter) er der ikke fejl - burde der ikke være det?~~
- ~~hvis der er kolon i body/description fucker det op (det er allowed, right - fordi det er der sådan set ikke i CFG'en)~~

**Comment by blitzher** [comment]
Trivielt løst ved at bruge
```cpp
body += ReadWords();
if (ctoken.type == ETT_OPEN_BRACKET) {
    //read amount
}
else if // bør afslutte body{
}
else {
    body += ctoken.word;
}
```

**Comment by Lildhansen** [comment]
men den læser jo ikke amount når den læser brackets. den må også godt læse 7 closing brackets i streg. den skal bare læse brackets som normal tekst. og der er stadig tegn den ikke må læse, så kan ikke se hvordan det der løser det

**Comment by Lildhansen** [comment]
og der er stadig fejl ved 1, 3 og 4

**Comment by NikolajKrogh** [comment]
Jeg er enig i at hvis du staver et field forkert burde du få en fejl

Til det sidste punkt er det så ikke kun en fejl i terminalen? Fordi når vi generer html'en så kan vi jo bare sige i head'eren at vi bruger unicode
