### ISSUE TITLE
fix no need to add newline on end of rcp-file

### ISSUE THREAD

**Issue by Lildhansen** [blitzher/P4-lang#55]

**Comment by Lildhansen** [comment]
second to last token before EOF is removed - if it is a blank

**Comment by RedToad0** [comment]
jeg giver det gerne et forsøg når at jeg er færdig med det jeg er igang med men andre må også genre kigge på det

**Comment by RedToad0** [comment]
I have found something, af en eller anden grund bliver spaces og nl yeeted i den sidste ting op til EOF så spaghetti carbonara bliver gemt som spaghetticarbonara

den fejl der engenligt sker er at   
title:spaghetti carbonara  ikke matcher spaghetticarbonara

forstaar dog ikke helt hvorfor endnu men jeg kigger videre...
