### ISSUE TITLE
Parser metoder skal give fejl hvis de støder på ulovlige tegn

### ISSUE THREAD

**Issue by RedToad0** [blitzher/P4-lang#65]
Consider the following
**ReadWords**(), **ReadSeperatorOrWaitAtNextField**(), og **ReadWordsPredicate**()

**ParseKitchenware** og **ReadIngredient** bruger disse hjælpe metoder til at parse men som det er nu er det lovligt at skrive 
1. **Tags**: super sejt, pasta,:              <------ (Throws runtime error*)
2. **Kitchenware**: Mircowave,,,,,,,,     <------ (commar bliver yeeted)
3. **Ingredient**: Ost, pasta,               <------ (comma bliver yetted, missing ingredient)
4. Kitchenware: fryingpan (dl)             <------  (Throws runtime error*)

Der er 2 muligheder
I principet kan vi sige ata yeeting af commaer virker som bliver overholdt i forhold til vores CFG og så lave noget håndtering til ulovlige tegn.
Ellers har vi brug for noget der både kontroller at der altid er en identifier efterfuldt et komma og at der altid bliver brugt lovlige symboler. 

*runtime error:
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
make: *** [makefile:74: run] Aborted (core dumped)

**Comment by blitzher** [comment]
Til 1. og 4. bør der vel bare ske bedre error-handling i ReadIngredient og ReadAmount.

Til 2. ved jeg ikke helt præcis hvad den gør lige nu, men kan godt kigge på det.

Til 3. bør den lave Ost og Pasta korrekt, men er vel essentielt det samme problem som 2.

**Comment by Lildhansen** [comment]
is it also tested though?

**Comment by Lildhansen** [comment]
2 og 3 er løst i 6c796cfbfe7ae0c920df7b6d5c10bb7c4c1eda53 
2 giver fejl 
3 fjerner bare trailing comma

Mangler bare tests til dem begge
