### ISSUE TITLE
Recipes used as ingredients in other recipes are not really checked for errors, all they need is a title

### ISSUE THREAD

**Issue by KasperBahrentzAAU** [blitzher/P4-lang#88]

**Comment by blitzher** [comment]
std::filesystem::path fpath = std::filesystem::absolute(clargs.input_filepath);
std::filesystem::path ppath = fpath.parent_path();

auto rcp_ret = parse_recipe((ppath / ingr.name).string() + ".rcp");
// INSERT VISITOR HERE
if (rcp_ret.has_err)
{
	char* err = (char*)malloc(100);
	sprintf(err, "In %s: %s", ingr.name.c_str(), rcp_ret.err.c_str());
	error = err;
	longjmp(exit_jmp, 1);
}

**Comment by blitzher** [comment]
Det er bare fordi der ikke bliver kaldt nogen visitor på den recipe som parseren producerer, sålænge at parseren ikke klager, er den godtaget.

**Comment by KasperBahrentzAAU** [comment]
Super, lad os kalde den visitor så

**Comment by blitzher** [comment]
Closed with 3df13a5686a1d18afc63e669e579b0bd2dd43a7c
