### ISSUE TITLE
Recipes compiled as ingredients of other recipes have incorrect amounts in the instructions

### ISSUE THREAD

**Issue by KasperBahrentzAAU** [blitzher/P4-lang#89]

**Comment by blitzher** [comment]
Giv et eksempel, eller vær mere specifik, gerne begge.

**Comment by KasperBahrentzAAU** [comment]
![image](https://user-images.githubusercontent.com/74188293/166433263-865313f1-a0eb-41cf-909f-6db4fa997995.png)

Here you go. Mængderne er bare 0
