### ISSUE TITLE
EOF field testing

### ISSUE THREAD

**Issue by RedToad0** [blitzher/P4-lang#96]
- [x] Title:
- [x] Description:
- [x] Servings:
- [x] Time:  (any)
- [x] Tags:
- [x] Kitchenware:
- [x] Ingredients:
- [x] Instructions: - not sure where
- [x] Body - these are
- [x] Yield

**Comment by Lildhansen** [comment]
ikke sikker på hvad jeg gør for ingredient der ender på ref. den prøver at åbne de filer med * (hvilket jo giver fin mening), men det gør det lidt svært at teste,

dette var min test:
void ref_ingredient_before_eof_matches()
{
	test_lib::REGISTER;
	std::vector<std::string> ingredients = {"spaghetti","some spaghetti","half eaten spaghetti from yesterday"};
	
	std::string example_string;
	epicr::recipe rcp;
	for (auto ingredient : ingredients)
	{
		example_string = "title: pasta    ingredients: salt,pepper," + ingredient + "*";
		rcp = epicr::parse_string_silent(example_string).recipe;
		test_lib::expect_equal_i(rcp.ingredients.size(),3);
		test_lib::expect_equal_s(rcp.ingredients[2].name, ingredient);
		test_lib::expect_equal_b(rcp.ingredients[2].is_ingredient_ref,true);
	}
}

**Comment by Jaffenheimer** [comment]
All tasks ticked of, closing this

**Comment by RedToad0** [comment]
yes coming up 2s
