### ISSUE TITLE
It should be prohibited to specify a unit for recipes used as ingredients 

### ISSUE THREAD

**Issue by KasperBahrentzAAU** [blitzher/P4-lang#99]
E.g.

**Legal:**
ingredients: 
    spaghetti*

ingredients: 
    spaghetti* [2]

**Illegal:**
ingredients: 
    spaghetti* [2 dl]

**Comment by blitzher** [comment]
Er ikke 100% sikker på at jeg er helt enig. Endvidere, i det 2. legal eksempel *bliver* unit'et overskrevet i den importerede recipe.

**Comment by Lildhansen** [comment]
hvis en recipe skal kunne bruges som en ingrediens er man da nødt til at specify hvor mange af dem (som man jo gør med ingredienser), så den anden skal da være legal

**Comment by KasperBahrentzAAU** [comment]
Hvis man kan skrive hvilken som helst unit bliver det jo mega forvirrende for brugeren (hvem end der skal lave retten). Hvor mange servings svarer 2 dl til? Det er der ingen der ved, så hvordan ved brugeren hvor stor en portion der skal laves?

Det skal selvfølgelig være lovligt at specificere antal, men synes virkelig ikke det giver mening at kunne ændre på uniten.

**Comment by Jaffenheimer** [comment]
Resolved in f7ae0f8 closing this
